### ISSUE TITLE
Fix French translations of document identifiers

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bipm#39]
From https://github.com/metanorma/bipm-si-brochure/issues/193

From BIPM Janet Miles:

When referring to the Resolutions I’d provided you with the English description but not the French: in French the model for “CGPM Resolution X (YYYY)” would be
* Résolution X **_de la_** CGPM (YYYY)

And there’s another slight complication in that the wording is “**_de la_**” for the CGPM, but “**_du_**” for the CIPM and Consultative Committees:
* Recommandation 2 _**du**_ CCDS (1970)

If this proves problematic we’ll have to find another solution… On the French version of the BIPM website my shortest version of the references is:
* CCTF - Recommandation 2 (1970)

--------

I believe this is a Relaton issue. The data source at bipm-data-outcomes does not provide this text.

In realton-data-bipm, this text is provided:
https://github.com/relaton/relaton-data-bipm/blob/9fd0943b7b142a23903bee0a8386463736e1a1af/data/cipm/meeting/resolution/1948-00.yaml#L26-L40

```yaml
docid:
- id: CIPM Resolution (1948)
  type: BIPM
  primary: true
- id: CIPM Resolution (1948)
  type: BIPM
  primary: true
  language: en
  script: Latn
- id: CIPM Résolution (1948)
  type: BIPM
  primary: true
  language: fr
  script: Latn
docnumber: CIPM Resolution (1948)
```

So this is a task for @andrew2net , and there may be some impact to relator-render (@opoudjis )

**Comment by ronaldtse** [comment]
We need to decide whether "Résolution X de la CGPM (YYYY)" is an actual document identifier, or an in-content textual reference.

I'm discussing this with the BIPM right now, so please hold off for now.

**Comment by ronaldtse** [comment]
This issue is active again due to this guide: https://metanorma.github.io/bipm-editor-guides/documents/bipm-outcomes-en.html

@andrew2net can you please help address this? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse as I understans, we need to use these translations as references. We don't need to update document identifiers, correct?

**Comment by andrew2net** [comment]
- We need to add a French conjunctive "de la" for "CGPM" and a conjunctive "du" for other group names, correct?
- A conjunctive is placed between `resource-specific-id` and `group-name`. Should we add a conjunctive if a document doesn't have `resource-specific-id`?

**Comment by andrew2net** [comment]
Is this ok?
- CGPM resolution without number https://github.com/relaton/relaton-data-bipm/blob/19a1414b90ceb31a97bec6549079c8c16e1624c7/data/cgpm/meeting/resolution/1889-00.yaml#L37-L63
- CGPM resolution with a number https://github.com/relaton/relaton-data-bipm/blob/19a1414b90ceb31a97bec6549079c8c16e1624c7/data/cgpm/meeting/resolution/1901-01.yaml#L37-L63
- Another group name  recommendation https://github.com/relaton/relaton-data-bipm/blob/19a1414b90ceb31a97bec6549079c8c16e1624c7/data/ccem/meeting/recommendation/2005-01.yaml#L37-L63
- Decisions of the CIPM (since 2012) https://github.com/relaton/relaton-data-bipm/blob/19a1414b90ceb31a97bec6549079c8c16e1624c7/data/cipm/meeting/decision/2012-101-1.yaml#L35-L61
- Recommendations/Resolutions/Decisions of the JCRB https://github.com/relaton/relaton-data-bipm/blob/19a1414b90ceb31a97bec6549079c8c16e1624c7/data/jcrb/meeting/resolution/1999-2-3.yaml#L35-L61

**Comment by ronaldtse** [comment]
@andrew2net the French long identifiers are wrong.

```
- id: CGPM Résolution 1 de la (1901)
  type: BIPM-long
  primary: true
  language: fr
  script: Latn
- id: CGPM Resolution 1 (1901) / CGPM Résolution 1 de la (1901)
  type: BIPM-long
  primary: true
```

They should be:

```yaml
- id: Résolution 1 de la CGPM (1901)
  type: BIPM-long
  primary: true
  language: fr
  script: Latn
- id: CGPM Resolution 1 (1901) / Résolution 1 de la CGPM (1901)
  type: BIPM-long
  primary: true
```

Please fix this ASAP.
