### ISSUE TITLE
Handling citation of Resolutions (CIPM and CGPM)

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#5]
@andrew2net we have these Resolutions that can be cited:
* https://github.com/metanorma/cgpm-resolutions/
* https://github.com/metanorma/cipm-resolutions/

What is the best way to enable the citation of them?

cc: @opoudjis

**Comment by andrew2net** [comment]
@ronaldtse what do we need to cite? If we need to cite the `dates` element:
```yaml
- dates:
  - 2012-06-01
  title: Decision CIPM/101-1
  identifier: 101-1
  url: https://www.bipm.org/en/committees/cipm/meeting/101(I).html
  reference: https://www.bipm.org/utils/en/pdf/CIPM/CIPM2012-EN.pdf
  considerations: []
  actions: []
  subject: The CIPM
  x-unparsed:
  - agreed that the minutes of the 100th meeting (2011) were confirmed by correspondence
    and that the printed version tabled is a true copy of what was circulated.
```
then it needs to be converted into relaton-iho model. Assume the mapping could be the following:
- date (2012-06-01) -> `date[@type='published']`
- title -> `title`
- identifier -> `docidentifier`
- url -> `url[@type='src']`
- reference -> `url[@type='doi']`
- considerations -> ?
- actions -> ?
- subject -> ?
- x-unparsed -> ?

Do you have suggestions on how to map `considerations`, `actions`, `subject`, and `x-unparsed`?
