### ISSUE TITLE
BIPM CIPM RES 1 citation is unstable

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bipm#55]
I include BIPM CIPM RES 1 in my metanorma-standoc test data. This reference is repeatedly switching with updates to relaton-bipm between pointing to an 1879 document, and pointing to a 1956 document, and has just done so again:

1879:

````
<uri type="citation" language="en" script="Latn">https://www.bipm.org/en/committees/ci/cipm/4-1879/resolution-</uri>
                <uri type="src" language="en" script="Latn">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cipm/meetings-en/meeting-4.yml</uri>
````

1956:

````
<uri type="citation" language="en" script="Latn">https://www.bipm.org/en/committees/ci/cipm/46-1956/resolution-1</uri>
               <uri type="src" language="en" script="Latn">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cipm/meetings-en/meeting-46.yml</uri>
````

This seems to indicate some kind of ambiguity, but it does need to be resolved.

**Comment by opoudjis** [comment]
See, the problem is, it changes between different versions of relaton-bipm. To get 1879, just go back to last week's version of relaton-bipm (and, maybe, the database it is reading.) But this is an ongoing issue, of flipping between the 1879 and the 1956 document, which has happened on relaton-bipm update at least 3 times, and I'm asking for analysis of why it is happening. Is the 1879 document unnumbered, and sometimes that's treated as zero, sometimes as 1?

The 1956 document has:

````
resolutions:
- dates:
  - '1956-10-06'
  subject: CIPM
  type: resolution
  title: Definition of the unit of time (second)
  identifier: 1
  url: https://www.bipm.org/en/committees/ci/cipm/46-1956/resolution-1
````

The 1879 document has:

````
resolutions:
- dates:
  - '1879-10-13'
  subject: CIPM
  type: resolution
  title: Signes abréviatifs pour les poids et mesures métriques
  identifier: 1879
  url: https://www.bipm.org/en/committees/ci/cipm/4-1879/resolution-
````

Notice, not resolution-1, just resolution. The current implementation does not match it to CIPM RES 1, but the previous one did...
